CREATE TABLE employee (
empID INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
firstName VARCHAR(50) NOT NULL,
lastName VARCHAR(50) NOT NULL,
loginAttempt TINYINT DEFAULT 0,
lastAttemptTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
isActive BOOLEAN DEFAULT TRUE,
positionID VARCHAR(10) NOT NULL,
email VARCHAR(100) NOT NULL,
gender TINYINT(1) NOT NULL
);
drop table employee